### ISSUE TITLE
good use of class

### ISSUE THREAD

**Issue by rimmesbe** [jamlol/prj-rev-bwfs-dasmoto#4]
This `price` class if very good. The name describes the component being styled making it very reusable. If you want you could swap out the `span` tags for `<strong>` tags which default to bold and add some semantic importance to the text.

https://github.com/jamlol/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/resources/style.css#L31-L34

**Comment by jamlol** [comment]
Swapped span for strong!
